create extension if not exists pgcrypto;

create table if not exists public.nexio_trades (
  id uuid primary key default gen_random_uuid(),
  symbol text not null,
  direction text not null check (direction in ('LONG')),
  signal_type text not null default 'RETEST_RECLAIM',
  status text not null default 'OPEN' check (status in ('OPEN','CLOSED','CANCELLED')),
  outcome text check (outcome is null or outcome in ('WIN','LOSS','SCRATCH','TIMEOUT')),
  entry numeric not null,
  initial_sl numeric not null,
  active_sl numeric not null,
  tp1 numeric not null,
  tp2 numeric not null,
  risk_per_unit numeric not null,
  entry_bar_close bigint not null,
  last_checked_bar_close bigint,
  breakeven_armed boolean not null default false,
  setup_score numeric not null,
  setup jsonb not null default '{}'::jsonb,
  btc_regime jsonb not null default '{}'::jsonb,
  fee_bps numeric not null default 5,
  entry_slippage_bps numeric not null default 0,
  exit_price numeric,
  exit_reason text,
  gross_pnl_pct numeric,
  net_pnl_pct numeric,
  r_multiple numeric,
  mfe_pct numeric not null default 0,
  mae_pct numeric not null default 0,
  alert_sent boolean not null default false,
  created_at timestamptz not null default now(),
  closed_at timestamptz,
  unique(symbol, entry_bar_close, signal_type)
);

create unique index if not exists nexio_one_open_trade_per_symbol
  on public.nexio_trades(symbol) where status = 'OPEN';
create unique index if not exists nexio_one_open_trade_global
  on public.nexio_trades((true)) where status = 'OPEN';
create index if not exists nexio_trades_created_at_idx
  on public.nexio_trades(created_at desc);
create index if not exists nexio_trades_open_idx
  on public.nexio_trades(status) where status = 'OPEN';

create table if not exists public.nexio_events (
  id bigint generated by default as identity primary key,
  event_key text not null unique,
  event_type text not null,
  symbol text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.nexio_trades enable row level security;
alter table public.nexio_events enable row level security;

-- This worker is designed to use SUPABASE_SERVICE_ROLE_KEY on Railway.
-- Never expose that key in a browser or mobile client.
-- The global partial index intentionally enforces MAX_OPEN_TRADES=1 even if
-- two Railway instances race. Close legacy duplicate OPEN rows before running
-- this migration if the index reports a uniqueness error.
